version: '2.1'

services:
    intercom2dw:
        image: pmsipilot/intercom2dw
        links:
            - db:db
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
            INTERCOM2DW_CRON: 0 */12 * * *
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d intercom2dw"]
            interval: 5s
            timeout: 60s
            retries: 3
