version: '2.1'

services:
    intercom2dw:
        image: node:8.2
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
        links:
            - db:db
        volumes:
            - .:/src
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:9.6
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U intercom2dw -d intercom2dw"]
            interval: 5s
            timeout: 60s
            retries: 3
