intercom2db:
    image: node:8.1
    environment:
        POSTGRES_USER: intercom2db
        POSTGRES_PASSWORD: intercom2db
        POSTGRES_DB: intercom2db
    links:
        - db:db
    volumes:
        - .:/src

db:
    image: postgres:9.6
    volumes:
        - ./schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./data/db:/var/lib/postgresql/data
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: intercom2db
        POSTGRES_PASSWORD: intercom2db
        POSTGRES_DB: intercom2db

metabase:
    image: metabase/metabase
    links:
        - db:db
    ports:
        - 3000:3000
    #volumes:
    #    - ./data/metabase:/metabase-data
    environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: metabase
        MB_DB_PORT: 5432
        MB_DB_USER: intercom2db
        MB_DB_PASS: intercom2db
        MB_DB_HOST: db