version: '2'

services:
    intercom2dw:
        image: pmsipilot/intercom2dw
        links:
            - db:db
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
        restart: always

    db:
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: intercom2dw
            POSTGRES_PASSWORD: intercom2dw
            POSTGRES_DB: intercom2dw
        restart: always
