#!/bin/sh

printenv | sed 's/^\([a-zA-Z0-9_]*\)=\(.*\)$/export \1="\2"/g' > /app/.env
echo "${INTERCOM2DW_CRON} . /app/.env; /app/intercom2dw ${@} >> /proc/$$/fd/1 2>&1" > /app/.cron
crontab /app/.cron

cron -f