name: Check

on:
  push:
    branches:
      - '*'

jobs:
  yarn-checks:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run cs

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run changelog-lint
